### ISSUE TITLE
Syntax errors in template now show minified location

### ISSUE THREAD

**Issue by monken** [monken/cfn-include#13]
since the introduction of jsmin, if there is a syntax error in the template, the output is no longer helpful. It is always `line 1`.

@hoegertn thoughts?

e.g.

```
Unhandled rejection Error: Parse error on line 1:
...f":"AWS::Region"}}},}}}}}}
-----------------------^
Expecting 'STRING', got '}'
```

**Comment by hoegertn** [comment]
Currently I have no idea. The problem ist that verifying the unminified template does not help either as it is not necessarily a valid JSON due to comments that are now possible. Maybe we can leave the helpful validation to the IDE that is used to create the template.

**Comment by monken** [comment]
I agree, the IDE should be able to help. However, I'd still like have this resolved so I'll keep the issue open.

**Comment by monken** [comment]
won't fix. Works fine with YAML templates.
