### ISSUE TITLE
Add a cli flag to include Metadata CfnInclude

### ISSUE THREAD

**Issue by rjcoelho** [monken/cfn-include#30]
I'm using this tool to include other yaml/json into a non-cfn yaml file, so adding
```
Metadata:
  CfnInclude:
    BuildDate: '2018-02-15T14:24:46.773Z'
    GitCommit: 2b49e091cb8891812d19b41380aade82f05cd79a
```
messes up my result.

I propose a --include-metadata flag to include this snippet, otherwise dont.

**Comment by monken** [comment]
fixed with 0d8fb0f263a785f2c62bc1056811ff5fa842900e
