### ISSUE TITLE
nomnom package is deprecated

### ISSUE THREAD

**Issue by bamapookie** [monken/cfn-include#31]
From nomnom's github page (https://github.com/harthur/nomnom):

Nomnom is deprecated. Check out https://github.com/tj/commander.js, which should have most, if not all of the capability that nomnom had. Thank you!

**Comment by monken** [comment]
good point, especially considering the latest madness by the `npm` team which simply released a v2.0.0 with just a deprecation notice and no code: https://github.com/zaach/jsonlint/issues/103#issuecomment-367416531
