### ISSUE TITLE
cfn-include is failing with following error. 

### ISSUE THREAD

**Issue by PreetiCK** [monken/cfn-include#32]
Hi,
{ Error: connect ETIMEDOUT 54.230.14.37:443
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.230.14.37',
  port: 443 }

cfn-include 0.9.0 version is working fine. The issue is with latest version 0.11.3.

Please let me know how to resolve.
 Thanks in Advance

**Comment by monken** [comment]
Hi, any chance you can provide a minimal example template that throws this error with v0.11.3?

Thanks!
