### ISSUE TITLE
AWSTemplateFormatVersion being changed

### ISSUE THREAD

**Issue by robertkeizer** [monken/cfn-include#33]
I have a template that starts off with the following line:

```
AWSTemplateFormatVersion: 2010-09-09
```

Running `cfn-include path/to/template` I end up with a file that contains the following:

```
  "AWSTemplateFormatVersion": "2010-09-09T00:00:00.000Z"
```

This fails tests locally and remotely as an invalid version.

**Comment by robertkeizer** [comment]
Adding strings around the date solved my issue.

`AWSTemplateFormatVersion: 2010-09-09` becomes `AWSTemplateFormatVersion: '2010-09-09'`

**Comment by sparr** [comment]
Please re-open this. Despite there being a workaround it's still a bug.
