### ISSUE TITLE
Lodash merge is limited

### ISSUE THREAD

**Issue by nmccready** [monken/cfn-include#42]
Big down side is Arrays are not merged correctly upon deep merge. I believe _.merge should be swapped out for deepmerge.
issue: https://stackoverflow.com/questions/39246101/deep-merge-using-lodash
https://www.npmjs.com/package/deepmerge

**Comment by monken** [comment]
This would be a breaking change since some people might rely on this behavior. We could add a `Fn::DeepMerge` function?

**Comment by nmccready** [comment]
Yes this would be more than acceptable. I'd rather not have to fork this library :D

**Comment by nmccready** [comment]
I have a PR coming almost done

**Comment by nmccready** [comment]
Done https://github.com/monken/cfn-include/pull/43

**Comment by nmccready** [comment]
Anyway this can be looked at today? Sorry just trying to decide if I need to publish this under my own scope for now .

**Comment by nmccready** [comment]
@monken any 👀  on this yet?
