### ISSUE TITLE
Adding quotes around CloudFormation functions in YAML

### ISSUE THREAD

**Issue by jeremydrichardson** [monken/cfn-include#47]
When using functions such as Fn::GetAtt or Fn::Sub and outputting YAML, quotes are added to the entry meaning CloudFormation will no longer process as a function.

**Comment by monken** [comment]
Hi Jeremy, could you provide an example?

The following is definitely valid yaml and understood by CloudFormation:

```yaml
'Fn::Sub': ${AWS::AccountId}
```

**Comment by jeremydrichardson** [comment]
Apologies, I misinterpreted the error I was getting in CloudFormation.

It had to do with how the CORS statement was being rewritten. I think I tried to correct it but instead broke it.

My source YAML had the following CORS line:
`Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"`

cfn-include transformed this to
`Cors:
        AllowHeaders: '''*'''
        AllowMethods: '''*'''
        AllowOrigin: '''*'''`

I think I was thrown off by the 3 single quotes all together and modified it by hand before deploying (though that was Friday and I can't exactly remember now...). But that cfn-include syntax appears to be correct and the deployment went through fine this morning.

Perhaps you can point me in the direction of where that type quoting makes sense? How does CloudFormation interpret that? 

Anyway, aside from that this issue can be closed, it wasn't actually a problem.

**Comment by monken** [comment]
Hi Jeremy, personally, I prefer the JSON output from `cfn-include`. That allows me to verify that my input YAML got interpreted correctly. YAML is a quite complex language. The JSON output on the other hand, can verify easily be verified. These two are equivalent:

```js
// echo "AllowMethods: \"'*'\"" | cfn-include
{
  "AllowMethods": "'*'"
}
```

```yaml
# echo "AllowMethods: \"'*'\"" | cfn-include -y
AllowMethods: '''*'''
```
