### ISSUE TITLE
syntax errors in yaml after include

### ISSUE THREAD

**Issue by adrian-grajdeanu** [monken/cfn-include#49]
template.yml:
```
!Include ./payload.yml
anotherkey: value
```
payload.yml
```
key: value
```
command that fails:
```
>cfn-include template.yml 
SyntaxError: YAMLException: end of the stream or a document separator is expected at line 2, column 11:
    anotherkey: value
              ^,SyntaxError: Unexpected token ! in JSON at position 0
>
```

**Comment by adrian-grajdeanu** [comment]
These are the yml files mentioned above, with .txt extension tagged due to github restrictions.
[template.yml.txt](https://github.com/monken/cfn-include/files/6092942/template.yml.txt)
[payload.yml.txt](https://github.com/monken/cfn-include/files/6092943/payload.yml.txt)

**Comment by adrian-grajdeanu** [comment]
Replacing !Include with Fn::Include: seems to be working.
template.yml
```
Fn::Include: ./payload.yml
anotherkey: value
```

**Comment by monken** [comment]
Alternatively:

```
Fn::Merge:
  - !Include payload.yml
  - anotherkey: value
```
