### ISSUE TITLE
path-parse seems to fail on URLs with query string

### ISSUE THREAD

**Issue by monken** [monken/cfn-include#5]

**Comment by hoegertn** [comment]
Can you provide a failing test for this bug, I can then try to fix it. But currently I am not sure what the problem really is about.

**Comment by monken** [comment]
it's only failing on Windows. I found the culprit by I need some more testing time on a Windows box. Travis unfortunately doesn't test on Windows yet :(

**Comment by hoegertn** [comment]
Can you outline some steps to reproduce it, I can then have a look at it on a Windows machine.

**Comment by monken** [comment]
Download this template and try compiling it: https://raw.githubusercontent.com/monken/cfn-include/master/examples/linuxami.template
