### ISSUE TITLE
Include metadata in complied template

### ISSUE THREAD

**Issue by monken** [monken/cfn-include#6]
with the following info
* date/time of compilation
* git commit checksum if available
* version string passed from to CLI

**Comment by hoegertn** [comment]
What exactly is missing? As I see it, these values are in the compiled output.

**Comment by monken** [comment]
The last point is missing where the user can pass a custom version string in the command line that is being included in the Metadata piece. Not sure if that is really useful. What are your thoughts?

**Comment by hoegertn** [comment]
I am not sure if this is really needed. I am planning to not running cfn-include manually but putting all files in git an have a CI job build and upload the compiled templates. So the commit hash is the version string I need and I do not want to add anything per cli args.

**Comment by monken** [comment]
Yeah, I don't know if that's practical. I'll leave it at this.
