### ISSUE TITLE
Any plans to release a new version?

### ISSUE THREAD

**Issue by whitfin** [monken/cfn-include#60]
I've noticed that the latest release was many years ago, but there's a lot of fun new stuff in the main branch. Unfortunately there's a dependency on `@cfn-include/utils` which appears to be a private package, so it's not possible to use from this repository.

Is there any plan to make that package public and/or create a new public release of this project? Thank you :)

**Comment by monken** [comment]
@nmccready any chance we can bake @cfn-include/utils into the main package? I see that it has a bunch of dependencies but I assume they are only required at build time? I'd hate to see the number of dependencies for cfn-include balloon (CDK is a heavy beast).

**Comment by nmccready** [comment]
We likely can if I get a free minute I’ll take a look at detaching it.

We could publish it as a separate package as well. It is this way at C1 cft-utils should be able to pre-cache each release to relive the runtime dependencies.

**Comment by nmccready** [comment]
We also need to update the entire CI process to make sure it passes tests either the new stuff.


I have some existing GitHub actions in other repos that will handle auto releases as well. Otherwise other admins will need access to publish the npm package.

**Comment by nmccready** [comment]
I am going to relocate `@cfn-include/utils` to `@znemz/cft-utils` for quicker publishing and since I am the original author. I make sure aws-cdk is only needed for pre-publish / dev.

**Comment by nmccready** [comment]
cft-utils work here https://github.com/nmccready/cft-utils working on auto publishing

**Comment by nmccready** [comment]
Fix

https://github.com/monken/cfn-include/issues/60

**Comment by nmccready** [comment]
Note: we should copy over these work flows https://github.com/nmccready/cft-utils/tree/main/.github/workflows

**Comment by nmccready** [comment]
https://github.com/monken/cfn-include/issues/70

**Comment by nmccready** [comment]
https://github.com/monken/cfn-include/issues/62 Resolved

**Comment by nmccready** [comment]
Forked the repo and published to npm under @znemz/cfn-include

https://github.com/nmccready/cfn-include

https://www.npmjs.com/package/@znemz/cfn-include
