### ISSUE TITLE
Put `Fn::Eval` behind CLI switch

### ISSUE THREAD

**Issue by monken** [monken/cfn-include#62]
I would want cfn-include to remain clear of `eval` unless explicitly enabled through a CLI switch. A template could contain malicious code in the eval block and we would happily execute it. Instead, I'd suggest we would fail the Fn::Eval block and ask the user to pass a `--eval` switch to the CLI to enabled it. @nmccready what are your thoughts? Any other risky functions you can think of?

**Comment by nmccready** [comment]
Fine with me I believe that’s the only one.

**Comment by nmccready** [comment]
This also includes `Fn::IfEval` as well

**Comment by nmccready** [comment]
Done https://github.com/monken/cfn-include/pull/63
